### ISSUE TITLE
cordova build android get error

### ISSUE THREAD

**Issue by moh3n9595** [crosswalk-project/cordova-plugin-crosswalk-webview#158]
I try to use crooswalk but I get this error, where is the problem?
```
BUILD FAILED
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
Total time: 1 mins 45.205 secs
Error: cmd: Command failed with exit code 1 Error output:
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'android'.
> Could not resolve all dependencies for configuration ':_armv7DebugApkCopy'.
   > Could not resolve org.xwalk:xwalk_core_library:23+.
     Required by:
         project :
      > Could not resolve org.xwalk:xwalk_core_library:23+.
         > Failed to list versions for org.xwalk:xwalk_core_library.
            > Unable to load Maven meta-data from https://jcenter.bintray.com/org/xwalk/xwalk_core_library/maven-metadata.xml.
               > Could not GET 'https://jcenter.bintray.com/org/xwalk/xwalk_core_library/maven-metadata.xml'.
                  > Connect to jcenter.bintray.com:443 [jcenter.bintray.com/108.168.243.150] failed: Connection timed out: connect
      > Could not resolve org.xwalk:xwalk_core_library:23+.
         > Failed to list versions for org.xwalk:xwalk_core_library.
            > Unable to load Maven meta-data from https://download.01.org/crosswalk/releases/crosswalk/android/maven2/org/xwalk/xwalk_core_library/maven-metadata.xml.
               > Could not GET 'https://download.01.org/crosswalk/releases/crosswalk/android/maven2/org/xwalk/xwalk_core_library/maven-metadata.xml'.
                  > Connect to download.01.org:443 [download.01.org/184.24.203.111] failed: Connection timed out: connect

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

```

**Comment by rakuco** [comment]
> Could not GET 'https://download.01.org/crosswalk/releases/crosswalk/android/maven2/org/xwalk/xwalk_core_library/maven-metadata.xml'.

> Connect to download.01.org:443 [download.01.org/184.24.203.111] failed: Connection timed out: connect

Are you able to access the URL above in your browser? It looks like either a temporary network issue on our side or a problem with your connection (especially if you're behind a proxy).

**Comment by VovanSuper** [comment]
The url, actually isn't available:
```
An error occurred while processing your request.
Reference #30.f7e5f33f.1504296444.a9b77e3
```

**Comment by LuizTokuhara** [comment]
Yes the url is down... Same error message on request.

**Comment by jhamil-conaca-coderoad-com** [comment]
The same error persist.

**Comment by Bodeclas** [comment]
Same error here!

**Comment by reyiyo** [comment]
+1

**Comment by RicardoBer** [comment]
Me too

**Comment by RicardoBer** [comment]
This can solve the issue for latest crosswalk version.

Open platforms\android\cordova-plugin-crosswalk-webview\eqp-xwalk.gradle

change this:

dependencies {
 xwalkSpec
}

to this one:

dependencies {
  compile 'org.xwalk:xwalk_core_library:23.53.589.4' //xwalkSpec
}

It works ok for two hours, now It has another problem, long time stoped in "Incremental java compilation is an incubating feature".

**Comment by blogui91** [comment]
Same issue here, ill try to do as you say @RicardoBer . thanks

**Comment by blogui91** [comment]
@RicardoBer  After some minutes with the issue that you said, the application compiled correctly, however it's the the solution :/

**Comment by LuizTokuhara** [comment]
Last week it was ok, today I got this problem... The sad thing is that I need to use the version 18 as I got some compatibility problems with the last version.
@rakuco Do you got any info on what is the problem?

**Comment by xiaohui-zhangxh** [comment]
@RicardoBer this works for me, thanks.

**Comment by RicardoBer** [comment]
Execute some apk with your version of crosswalk, open chrome inspector, open console and type:

navigator.userAgent

You can see the version of crosswalk (latest one is 23.53.589.4).

Replace in the previous post.

**Comment by RicardoBer** [comment]
It' is down again the good way is not touch this, but it seem they don't make it up. I have this error again when create new android platform.

**Comment by daggeto** [comment]
Still have same problem. Event after `compile 'org.xwalk:xwalk_core_library:23.53.589.4'`. Also console agen shows nothing

**Comment by Jun711** [comment]
just wonder if you guys are using cordova-plugin-crosswalk-webview@2.3.0? Thanks!

**Comment by RicardoBer** [comment]
Yes, the latest one, that is the reason for 23.53.589.4

**Comment by Jun711** [comment]
I guess for now, I have use earlier version then.

**Comment by RicardoBer** [comment]
Please, read above, I put how to check your crosswalk version there.

**Comment by liuya891012** [comment]
what can i do with @2.1.0? because i used other SDK,can not run in  chrome with inspector

**Comment by zhouzhongyuan** [comment]
You can use this plugin temporarily:
```
cordova plugin add https://github.com/zhouzhongyuan/cordova-plugin-crosswalk-webview
```
It just fixed this error.

**Comment by xiaohui-zhangxh** [comment]
Actually, you don't need to change any code within plugin, just put below config to cordova config.yml:

    <preference name="xwalkVersion" value="xwalk_core_library:23.53.589.4" />

See https://github.com/crosswalk-project/cordova-plugin-crosswalk-webview in section `Configure `

**Comment by ZhongQ** [comment]
I have the same problem. Now I have solved it. Thank you. @RicardoBer

**Comment by kaynz** [comment]
Thanks @xiaohui-zhangxh

**Comment by realyze** [comment]
@xiaohui-zhangxh Hmm does that actually work for you?
I'm getting
```
Could not GET
   'https://download.01.org/crosswalk/releases/crosswalk/android/maven2/org/xwalk/xwalk_core_library/23.53.589.4/xwalk_core_library-23.53.589.4.pom'.
   Received status code 503 from server: Service Unavailable
```

And the build is still broken.

**Comment by kaynz** [comment]
@realyze That's working for me :)

**Comment by realyze** [comment]
@kaynz Interesting. Maybe you have the xwalk version cached or something? Or maybe it depends on where you are... If the maven repo would consistently return HTTP 503, I don't see how it would work for anyone.

**Comment by kaynz** [comment]
@realyze Yea, that's right. As soon as you clean your mvn cache, you won't get your builds done.

**Comment by xiaohui-zhangxh** [comment]
@realyze you can check your network with this command:

    curl https://download.01.org/crosswalk/releases/crosswalk/android/maven2/org/xwalk/xwalk_core_library/23.53.589.4/xwalk_core_library-23.53.589.4.pom

On my side this URL returns correct XML file:

```
<?xml version="1.0" encoding="UTF-8"?>
<!--
This file is generated automatically.
-->
<project xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <modelVersion>4.0.0</modelVersion>
  <groupId>org.xwalk</groupId>
  <artifactId>xwalk_core_library</artifactId>
  <version>23.53.589.4</version>
  <packaging>aar</packaging>

  <!-- Crosswalk itself does not depend on external libraries, but it inherits
       some dependencies from Chromium itself. -->
  <dependencies>
    <dependency>
      <groupId>com.android.support</groupId>
      <artifactId>support-v4</artifactId>
      <version>[13.0.0,)</version> <!-- >= 13.0.0 -->
      <scope>runtime</scope>
    </dependency>
  </dependencies>
</project>
```

**Comment by kaynz** [comment]
@xiaohui-zhangxh 
```

<HTML><HEAD><TITLE>Error</TITLE></HEAD><BODY>
An error occurred while processing your request.<p>
Reference&#32;&#35;30&#46;95e5f33f&#46;1504515797&#46;b086f0f
</BODY></HTML>
```

**Comment by xiaohui-zhangxh** [comment]
That's strange, I can get this URL correctly for now.

<img width="931" alt="screenshot 2017-09-04 at 5 05 07 pm" src="https://user-images.githubusercontent.com/674321/30019465-43669972-9193-11e7-93c4-807de936e78e.png">

**Comment by kaynz** [comment]
Okay, that's interesting. I'm getting HTTP 503 from my local computer. And HTTP 200 from my server (which is +-100km away from my position).

**Comment by rakuco** [comment]
I've closed several other tickets and would like to centralize all the discussions here. I've sent [an email](https://lists.crosswalk-project.org/pipermail/crosswalk-help/2017-September/002465.html) to both of our mailing lists.

We're trying to figure out what's going on, but this downtime was not caused by us; proper action might only be taken tomorrow though due Labor Day in the US.

**Comment by QuentinRoy** [comment]
@zhouzhongyuan ` https://github.com/zhouzhongyuan/cordova-plugin-crosswalk-webview` does not work on mine.

**Comment by cristianoaredes** [comment]
Same error here, someone managed to solved the problem?

**Comment by silvairsoares** [comment]
![erro crosswalk](https://user-images.githubusercontent.com/18450095/30038030-1f82e73c-9197-11e7-9cfe-2426edc7420e.jpg)

What a sad face! I get this same error here in Brazil.

**Comment by DAKZH** [comment]
+1

**Comment by DAKZH** [comment]
started working now!

**Comment by realyze** [comment]
I'm now getting HTTP 503 on CircleCI on https://download.01.org/crosswalk/releases/crosswalk/android/maven2/org/xwalk/xwalk_core_library/maven-metadata.xml

**Comment by realyze** [comment]
The whole https://download.01.org domain seems to be down, actually.

**Comment by MarshallMathersIII** [comment]
what can i say

**Comment by MarshallMathersIII** [comment]
i use this url
```
dependencies {
compile 'org.xwalk:xwalk_core_library:23.53.589.4' //xwalkSpec
}
```
but the following error occurred
![image](https://user-images.githubusercontent.com/16094782/30043558-9e0bdf1c-922a-11e7-969e-d6c6a06d8763.png)

**Comment by zhouhaiou** [comment]
me too

**Comment by xiaohui-zhangxh** [comment]
@MarshallMathersIII you should set android minSdkVersion to 16

**Comment by beevelop** [comment]
Had a look at the 01.org DNS records and there might be a temporary workaround. There is a subdomain called `origin-download.01.org` which still serves the maven repository properly. But due to certificate problems I wasn't able to use without further configurations and workarounds. I therefore decided to provide a completely unofficial crosswalk mirror until this issue is resolved:
https://xwalk.beevelop.com/crosswalk/releases/crosswalk/android/maven2/org/

I was able to get the CI running again by replacing `download.01.org` with `xwalk.beevelop.com` in the `platforms/android/cordova-plugin-crosswalk-webview/foobar-xwalk.gradle`.

**Comment by TitanNano** [comment]
@beevelop 
```
>  sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
```

I'm using your mirror but get this error.

**Comment by beevelop** [comment]
@TitanNano This is most likely caused by Java not trusting the Let's Encrypt certificates. From Java 8u101 onwards it should work properly (refer to https://stackoverflow.com/questions/34110426/does-java-support-lets-encrypt-certificates).

**Comment by moh3n9595** [comment]
I test all of your suggestions but I get same error :)

**Comment by rajild** [comment]
+1

Website : https://download.01.org/crosswalk/releases/crosswalk/android/ 
is not accessible.  Crosswalk files are not being downloaded by plugin.

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'android'.
> Could not resolve all dependencies for configuration ':_armv7DebugApkCopy'.
   > Could not resolve org.xwalk:xwalk_core_library:23.53.589.4.
     Required by:
         project :
      > Could not resolve org.xwalk:xwalk_core_library:23.53.589.4.
         > Could not get resource 'https://download.01.org/crosswalk/releases/crosswalk/android/maven2/org/xwalk/xwalk_core_library/23.53.589.4/xwalk_core_library-23.53.589.4.pom'.
            > Could not HEAD 'https://download.01.org/crosswalk/releases/crosswalk/android/maven2/org/xwalk/xwalk_core_library/23.53.589.4/xwalk_core_library-23.53.589.4.pom'. Received status code 503 from server: Service Unavailable

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

**Comment by rajild** [comment]
@beevelop @TitanNano 
Your solution worked for me.  Thanks

**Comment by junvo** [comment]
Can someone explain please how to use the mirror from @beevelop ? 

I haven´t installed crosswalk yet.  I tried to use the command ionic cordova plugin add cordova-plugin-crosswalk-webview and then place a version by creating a xwalk folder in \plugins\cordova-plugin-crosswalk-webview\platforms\android\src\org

but that didnt worked.

**Comment by renanbandeira** [comment]
I just added the sed command on before_build hook and it worked fine! Just remember to change foobar-xwalk.gradle to your name's app

**Comment by junvo** [comment]
@renanbandeira thanks i was not familiar with the sed command instead i just changed the path in p\platforms\android\cordova-plugin-crosswalk-webview\starter-xwalk.gradle 

cdvPluginPostBuildExtras.add({
    def xwalkMavenRepo = 'https://xwalk.beevelop.com/crosswalk/releases/crosswalk/android/maven2';
    if (xwalkMode == LITE_MODE) {
        xwalkMavenRepo = 'https://xwalk.beevelop.com/crosswalk/releases/crosswalk-lite/android/maven2';
    }

and it works @beevelop thanks for the mirror!

**Comment by renraku88** [comment]
@beevelop it works for me, thanks!!

**Comment by rakuco** [comment]
download.01.org should be back up now; can anyone else test that it's working again?

**Comment by nicolas-rempulski** [comment]
@rakuco 

download.01.org is accessible from here and cordova builds succeeded without modifications.

Thanks !

**Comment by beevelop** [comment]
Seems to work properly 👍 For them `sed`-lovers:
```
sed -i 's/xwalk.beevelop.com/download.01.org/g' platforms/android/cordova-plugin-crosswalk-webview/foobar-xwalk.gradle
```

**Comment by silvairsoares** [comment]
@rakuco Thanks man!

![ok](https://user-images.githubusercontent.com/18450095/30074218-11e77330-9247-11e7-99c1-3fc9be2c9722.jpg)

**Comment by rakuco** [comment]
Thanks for the confirmations, I'm closing this issue as fixed.

**Comment by ee11131** [comment]
Both the https://xwalk.beevelop.com/crosswalk/releases/crosswalk/android/maven2 and download.01.org are down? Anyone else can confirm this?

**Comment by silvairsoares** [comment]
"download.01.org/crosswalk" is working.
"xwalk.beevelop.com/crosswalk" is offline.

![1](https://user-images.githubusercontent.com/18450095/32563267-f5ac23b8-c497-11e7-8853-915736c277b1.jpg)

![2](https://user-images.githubusercontent.com/18450095/32563268-f5d81518-c497-11e7-8260-3d47c95ea7ff.jpg)

**Comment by mahdi313s** [comment]
hi
i can get :
https://download.01.org/crosswalk/releases/crosswalk/android/maven2/org/xwalk/xwalk_core_library/23.53.589.4/xwalk_core_library-23.53.589.4.pom

but i get this error:

* What went wrong:
A problem occurred configuring root project 'android'.
> Could not resolve all dependencies for configuration ':_armv7DebugApkCopy'.
   > Could not resolve org.xwalk:xwalk_core_library:23.53.589.4.
     Required by:
         project :
      > Could not resolve org.xwalk:xwalk_core_library:23.53.589.4.
         > Could not parse POM https://maven.google.com/org/xwalk/xwalk_core_library/23.53.589.4/xwalk_core_library-23.53.589.4.pom
            > Already seen doctype.
      > Could not resolve org.xwalk:xwalk_core_library:23.53.589.4.
         > Failed to download SHA1 for resource 'https://download.01.org/crosswalk/releases/crosswalk/android/maven2/org/xwalk/xwalk_core_library/23.53.589.4/xwalk_core_library-23.53.589.4.pom'.
            > For input string: "<!"
      > Could not resolve org.xwalk:xwalk_core_library:23.53.589.4.
         > Could not get resource 'https://jcenter.bintray.com/org/xwalk/xwalk_core_library/23.53.589.4/xwalk_core_library-23.53.589.4.pom'.
            > Could not HEAD 'https://jcenter.bintray.com/org/xwalk/xwalk_core_library/23.53.589.4/xwalk_core_library-23.53.589.4.pom'.
               > Connect to jcenter.bintray.com:443 [jcenter.bintray.com/108.168.243.150] failed: Connection timed out: connect

can anywone help me?

thanks

**Comment by niftynei** [comment]
same as @mahdi313s. curl seems to work fine though. is it possible this is an Android Studio v3 thing?

```
Unable to resolve dependency for ':app@debugAndroidTest/compileClasspath': Could not resolve org.xwalk:xwalk_core_library:23.53.589.4.

Could not resolve org.xwalk:xwalk_core_library:23.53.589.4.
Required by:
    project :app
 > Could not resolve org.xwalk:xwalk_core_library:23.53.589.4.
    > Failed to download SHA1 for resource 'http://download.01.org/crosswalk/releases/crosswalk/android/maven2/org/xwalk/xwalk_core_library/23.53.589.4/xwalk_core_library-23.53.589.4.pom'.
          > For input string: "<!"
```

**Comment by mahdi313s** [comment]
hi niftynei
The problem was Internet access for me.
I used Psiphon 3 with the settings as follows:
Locale Proxy Ports
Http / Https: 8088
Socks: 8089
And in the gradle.Prophetis folder, which I created on platforms\Android path, I entered the following settings:
systemProp.https.proxyPort = 8088
systemProp.http.proxyHost = 127.0.0.1
systemProp.https.proxyHost = 127.0.0.1
systemProp.http.proxyPort = 8088
This way the problem was resolved

**Comment by Topiya** [comment]
@RicardoBer 
```
FAILURE: Build failed with an exception.

        * What went wrong:
        A problem occurred configuring root project 'android'.
        > Could not resolve all dependencies for configuration ':_armv7DebugApkCopy'.
            > Could not resolve org.xwalk:xwalk_core_library:23.53.589.4.
              Required by:
                  project :
               > Could not resolve org.xwalk:xwalk_core_library:23.53.589.4.
                  > Could not get resource
        'https://repo1.maven.org/maven2/org/xwalk/xwalk_core_library/23.53.589.4/xwalk_core_library-23.53.589.4.pom'.
                     > Could not GET
        'https://repo1.maven.org/maven2/org/xwalk/xwalk_core_library/23.53.589.4/xwalk_core_library-23.53.589.4.pom'.
                        > sun.security.validator.ValidatorException: PKIX path building failed:
        sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to
        requested target
               > Could not resolve org.xwalk:xwalk_core_library:23.53.589.4.
                  > Could not get resource
        'https://jcenter.bintray.com/org/xwalk/xwalk_core_library/23.53.589.4/xwalk_core_library-23.53.589.4.pom'.
                     > Could not GET
        'https://jcenter.bintray.com/org/xwalk/xwalk_core_library/23.53.589.4/xwalk_core_library-23.53.589.4.pom'.
                        > sun.security.validator.ValidatorException: PKIX path building failed:
        sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to
        requested target
               > Could not resolve org.xwalk:xwalk_core_library:23.53.589.4.
                  > Could not get resource
        'https://download.01.org/crosswalk/releases/crosswalk/android/maven2/org/xwalk/xwalk_core_library/23.53.589.4/xwalk_core_library-23.53.589.4.pom'.
                     > Could not GET     'https://download.01.org/crosswalk/releases/crosswalk/android/maven2/org/xwalk/xwalk_core_library/23.53.589.4/xwalk_core_library-23.53.589.4.pom'.
                        > sun.security.validator.ValidatorException: PKIX path building failed:
        sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to
        requested target
```

I am getting this error while android build.
I have tried with your solution but still getting the same error. Can you please let me know what can the solution?

**Comment by RicardoBer** [comment]
Sorry @Topiya, I use with the propose solution, I use crosswalk for an ionic project, and after 1 year with this two I can only tell you that I propose to never, never, use ionic or crosswalk, lots of bugs an total lose of control for developer.

**Comment by mahdi313s** [comment]
tanks alot for your help


------------------------------ پیام اصلی ------------------------------
از: ‪RicardoBer <notifications@github.com>‬
به: ‪crosswalk-project/cordova-plugin-crosswalk-webview <cordova-plugin-crosswalk-webview@noreply.github.com>‬
رونوشت به: ‪mahdi313s <mahdi.s.94@chmail.ir>, Mention <mention@noreply.github.com>‬
ارسال شده: دوشنبه، 23 بهمن 1396 10:57:05
موضوع: Re: [crosswalk-project/cordova-plugin-crosswalk-webview] cordova build android get error (#158)

 

 

Sorry @Topiya, I use with the propose solution, I use crosswalk for an ionic project, and after 1 year with this two I can only tell you that I propose to never, never, use ionic or crosswalk, lots of bugs an total lose of control for developer.

&mdash;

**Comment by meisam3322** [comment]
Why cannot download by cordova ????

**Comment by gladishukD** [comment]
@RicardoBer Help me please!!!!!
I install crosswalk plagin and have a problem. tried methods described above, no results were given

it's result with console
C:\Users\user\user-portal-cordova>cordova build android
cordova-android-support-gradle-release: Android platform: cordova-android@6
cordova-android-support-gradle-release: Wrote custom version '26.+' to C:\Users\user\user-portal-cordova\platforms\android\build.gradle
cordova-android-support-gradle-release: Wrote custom version '26.+' to C:\Users\user\user-portal-cordova\platforms\android\cordova-android-support-gradle-release\properties.gradle
Before deploy hook started...
Checking is node modules installed...
Node modules already installed.
Starting webpack build...
Webpack build completed to www folder successfully!
Cordova hook completed. Resuming to run your cordova command...
cordova-android-support-gradle-release: Android platform: cordova-android@6
cordova-android-support-gradle-release: Wrote custom version '26.+' to C:\Users\user\user-portal-cordova\platforms\android\build.gradle
cordova-android-support-gradle-release: Wrote custom version '26.+' to C:\Users\user\user-portal-cordova\platforms\android\cordova-android-support-gradle-release\properties.gradle
ANDROID_HOME=C:\Users\user\AppData\Local\Android\sdk
JAVA_HOME=C:\Program Files\Java\jdk1.8.0_121
Subproject Path: CordovaLib
+-----------------------------------------------------------------
| cordova-android-support-gradle-release: 26.+
+-----------------------------------------------------------------
Configuration 'compile' in project ':' is deprecated. Use 'implementation' instead.
null
The Task.leftShift(Closure) method has been deprecated and is scheduled to be removed in Gradle 5.0. Please use Task.doLast(Action) instead.
        at build_1t7ogmoz3k6wt600n282zlm6v.run(C:\Users\user\user-portal-cordova\platforms\android\build.gradle:145)
org.xwalk:xwalk_core_library:23.53.589.4

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'android'.
> All flavors must now belong to a named flavor dimension. Learn more at https://d.android.com/r/tools/flavorDimensions-missing-error-message.html

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
(node:8800) UnhandledPromiseRejectionWarning: Error: cmd: Command failed with exit code 1 Error output:
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'android'.
> All flavors must now belong to a named flavor dimension. Learn more at https://d.android.com/r/tools/flavorDimensions-missing-error-message.html

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
    at ChildProcess.whenDone (C:\Users\user\user-portal-cordova\platforms\android\cordova\node_modules\cordova-common\src\superspawn.js:169:23)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
(node:8800) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting
 a promise which was not handled with .catch(). (rejection id: 1)
(node:8800) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with
a non-zero exit code.

**Comment by satara** [comment]
I am trying to build a project with Phonegap build that was working fine a month ago, but now I get the "Could not resolve org.xwalk:xwalk_core_library:23+" error. 
Is there any issues with the servers or is that a Phonegap issue?
I tried the code below in config.xml but it didn't work either (although the log did not report an error):

`<preference name="xwalkVersion" value="xwalk_core_library:23.53.589.4" />`

Any help? Thanks!

**Comment by gelks** [comment]
@satara same here, I'm getting a 504 on https://download.01.org/crosswalk/releases/crosswalk/android/maven2/org/xwalk/xwalk_core_library/maven-metadata.xml

**Comment by satara** [comment]
It is working again. Thanks!

**Comment by andypotato** [comment]
It seems down again - Currently there is a 504 error page
https://download.01.org/crosswalk/releases/crosswalk/android/maven2/org/xwalk/xwalk_core_library/maven-metadata.xml

**Comment by ajayashuba** [comment]
again the whole domain gives 504 timeout error plz suggest some alternatives

**Comment by mathieu21** [comment]
same here, down again

**Comment by ajayashuba** [comment]
same here too

**Comment by andypotato** [comment]
@rakuco could you kindly check the server and bring it back up? Very sorry to bother you, I'm just stuck here and can't build my App without this repository

**Comment by ottobit** [comment]
@andypotato link is still offline with **504 Gateway Time-out**. Any suggestions?

**Comment by rakuco** [comment]
It looks like 01.org is down again... I'll see if I can find out internally why this has been failing so often lately.

**Comment by phyr0s** [comment]
@rakuco @ottobit the service is down... Gateway Time-out


Failed to list versions for org.xwalk:xwalk_core_library.
         > Unable to load Maven meta-data from https://download.01.org/crosswalk/releases/crosswalk/android/maven2/org/xwalk/xwalk_core_library/maven-metadata.xml.
            > Could not HEAD 'https://download.01.org/crosswalk/releases/crosswalk/android/maven2/org/xwalk/xwalk_core_library/maven-metadata.xml'. Received status code 504 from server: Gateway Time-out

**Comment by oarsheo** [comment]
Download and unpack zip xwalk_core_library
https://drive.google.com/file/d/1uegNBJdfRrVJRlv3cq1MgjAEc4kPKFrE/view?usp=sharing
In file 
`platforms/android/cordova-plugin-crosswalk-webview/xwalk.gradle`
Replace:
`def xwalkMavenRepo = 'https://download.01.org/crosswalk/releases/crosswalk/android/maven2';`
Set path to unpacked zip:
`def xwalkMavenRepo = '/ARSHE/arshe/Desktop/mWallet_v4.0/CORE/';`

> remove `assets` `build` `.gradle`

**Comment by dmastag** [comment]
@oarsheo thanks for the suggestion though I can't do that since this is inside my CI Pipelines

**Comment by cegbert-wondersign** [comment]
@rakuco Is there an ETR (estimated time to repair) for this issue?

**Comment by rakuco** [comment]
No, but I think it shouldn't take long, the biggest problem's that the people responsible for 01.org are in the US west coast.

**Comment by rakuco** [comment]
... and we're back.

**Comment by jonaszuberbuehler** [comment]
@rakuco Thank you! Would be nice if there was a mirror site available for future incidents.

**Comment by citerio** [comment]
Hey @rakuco, I've been working on an Ionic 2 project since 3 years ago and everything's gone fine with crosswalk until now. My last build was last December and it worked fine as always, now I've been trying to generate a new build but I'm catching this error in the image below. I'm not behind a proxy or something, I can access the URL in my browser, it's something related to certificates. I hope you can help me.

![image](https://user-images.githubusercontent.com/9136205/74684983-93d5c180-51a3-11ea-9416-6e826b3850c3.png)

**Comment by rakuco** [comment]
Everything seems to be fine on the server side. The SSL certificate for download.01.org seems to have been renewed around mid-December last year, so my guess is that somehow your Java installation does not have the appropriate certificates in its trust store.

**Comment by citerio** [comment]
Problem solved. I had to download and manually add this certificate to the Java keystore, shit, it took so long for me to solve this issue but I made it, I wanna thank Github, rakuco and every single person that made this possible, thanks for your support, this prize is for you too.
